# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    env:
      TOKEN: ${{ secrets.TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      YOUTUBE_COOKIE: ${{ secrets.YOUTUBE_COOKIE }}
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
          touch .env
          echo TOKEN=$TOKEN >> .env
          echo CLIENT_ID=$CLIENT_ID >> .env
          echo GUILD_ID=$GUILD_ID >> .env
          echo SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID >> .env
          echo SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET >> .env
          echo SPOTIFY_REFRESH_TOKEN=$SPOTIFY_REFRESH_TOKEN >> .env
          echo YOUTUBE_COOKIE=$YOUTUBE_COOKIE >> .env
          echo NODE_ENV=production >> .env
    - run: npm i
    - run: npm run deploy
    - run: pm2 restart tocinitobot
